version: '3'
services:
  db:
    image: postgres:15.5
    container_name: db-habito-easy
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db-habito-easy
    volumes:
      - ./data:/data/postgres
    ports:
      - "25060:5432"
