version: '3'
services:
  db:
    image: postgres:15.5
    container_name: db-habito-easy
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db-habito-easy
    ports:
      - "25060:5432"

  mongo:
    image: mongo:6.0
    container_name: mongo-habito-easy
    hostname: mongodb
    env_file:
      - ../../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"